language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    allow_failures:
        - php: hhvm

    exclude:
        - php: hhvm
          env: PHP_BIN=php-cgi

script: ./vendor/bin/tester ./tests/cases

before_script:
    # Install Nette Tester
    - composer install --no-interaction --dev --prefer-source
